name: production

on:
  workflow_dispatch:

jobs:
  production:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository.
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Download snapshot.
        run: |
          curl "https://raw.githubusercontent.com/wlandau/staging/main/snapshot.url" -Lo snapshot.url
          cat snapshot.url | xargs curl -Lo snapshot.zip
          unzip snapshot.zip -d snapshot && rm -f snapshot.zip
      
      - name: Copy permanent files to snapshot.
        run: |
          cp index.html snapshot
          cp LICENSE.note snapshot
          cp snapshot.json snapshot
          cp snapshot.url snapshot

      - name: Install rversions.
        shell: Rscript {0}
        run: install.packages("rversions")

      - name: Record snapshot date.
        run: date +%F > snapshot/date.txt

      - name: Record snapshot R version.
        shell: Rscript {0}
        run: writeLines(rversions::r_release()$version, file.path("snapshot", "r_version.txt"))

      - name: Deploy snapshot to https://r-multiverse-production-test-wlandau.netlify.app.
        run: netlify deploy --dir=snapshot --prod --site $NETLIFY_SITE_ID
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
